### ISSUE TITLE
Consider making methods more modular

### ISSUE THREAD

**Issue by ecleary** [maythovens-third/Products#9]
https://github.com/maythovens-third/Products/blob/9759291a1442c42094f33402814208ab3e428888/server/middleware/controllers/controllers.js#L19-L79

The following applies to lines 19–39, 49–79:

It feels like the `getSpecificProduct` and `getProductStyles` methods may be doing more than one thing, which (if so) breaks the [single-responsibility principle](https://en.wikipedia.org/wiki/Single-responsibility_principle). If possible and if it makes sense, recommend trying to abstract some of this functionality out into separate methods (e.g. helper functions) to increase the readability and testability of the code.

**Comment by dootMaster** [comment]
moved data shaping functions into their own helpers file
